version: "3"
services:
  server:
    image: trzeci/emscripten-upstream
    container_name: emcc
    restart: always
    command: /bin/bash
    volumes:
      - .:/build/wasm
    stdin_open: true
    tty: true
